"erase": "擦除",
"approach": "方法",
"overwhelming": "势不可挡的",
"Interface request": "接口请求",
"trash": "垃圾",
"virtual": "事实上的",
"serial number": "序列号",
"serialize": "序列化",
"presentational": "表象的",
"relationship": "关系",
"proper": "适当的",
"overly": "过分地",
"complex": "复杂的",
"arrrangement": "排列",
"registry": "登记处",
"registry provider": "注册表提供者",
"hiearachical": "听力正常的",
"canonical": "典范的",
"delimiter": "定界符",
"expired": "",
"substract": "子集",
"Catalog": "目录",
"asynchronous": "异步",
"discard": "丢弃",
"revalidate": "再验证",
"vary": "变化",
"Propaganda": "宣传",
"propagandize": "宣传",
"intention": "意图",
"context": "语境",
"correct": "对的",
"mixins": "混入",
"stage": "阶段",
"explicitly": "明确地",
"cascade": "叶栅",
"ticks": "蜱类",
"overtime": "超时",
"second": "秒",
"Prompt": "提示",
"fantasy": "幻想",
"rely on": "依赖",
"omitted": "省略",
"turn": "转",
"tern": "燕鸥",
"semicolon": "分号",
"Quotation mark": "引号",
"Punctuation": "标点符号",
"Double quotation mark": "双引号",
"Abbreviation": "缩写",
"backquote": "反引号",
"arround": "环绕",
"Subsequently": "随后",
"classmates": "同学",
"Two digits": "两位数",
"Solve the problem": "解决问题",
"priority of use": "优先使用",
"auxiliary function": "辅助函数",
"Slash": "斜杠",
"Backslash": "反、斜杠",
