"erase": "擦除",
"approach": "方法",
"overwhelming": "势不可挡的",
"Interface request": "接口请求",
"style": "样式",
"trash": "垃圾",
"virtual": "事实上的",
"serial number": "序列号",
"serialize": "序列化",
"presentational": "表象的",
"relationship": "关系",
"proper": "适当的",
"overly": "过分地",
"complex": "复杂的",
"arrrangement": "排列",
"registry": "登记处",
"registry provider": "注册表提供者",
"hiearachical": "听力正常的",
"canonical": "典范的",
"delimiter": "定界符",
"expired": "",
"substract": "子集",
"Catalog": "目录",
"asynchronous": "异步",
"discard": "丢弃",
"revalidate": "再验证",
"vary": "变化",
"Propaganda": "宣传",
"propagandize": "宣传",
