"Multiple": "倍数",
"redundant": "冗余",
"qualifier": "限定词",
"suspicious comparison": "可疑比较",
"candidates": "候选人",
"equation": "方程",
"interrupt": "中断",
"triangle": "三角",
"Square": "乘方",
"Detailed list": "清单",
"need to be dealt with": "待办",
"Debate": "辩论",
"hybrid": "混合的",
"capactiy": "容量",
"delegate": "委托",
"repo": "回购协议",
"contravariant": "逆变",
"encryption": "加密",
"whale": "鲸鱼",
"dervied": "免除",
"instrumentation": "仪器仪表",
"explicit": "明确的",
"consultant": "顾问",
"strentch": "斯特伦奇",
"stretch": "伸展",
"Lexical Structure": "词法结构",
"counterpart": "对应部分",
"override": "重写",
"Succeeding": "后继",
"transaction": "交易",
"amout": "阿穆特",
"amount": "数量",
"profile": "简介",
"decompiler": "反编译程序",
"migrate": "迁移",
